export default {
  GET_WORKSHOPS_REQUEST: '@workshops/GET_WORKSHOPS_REQUEST',
  GET_WORKSHOPS_SUCCESS: '@workshops/GET_WORKSHOPS_SUCCESS',
  SUBSCRIBE_TO_WORKSHOP: '@workshops/SUBSCRIBE_TO_WORKSHOP'
};
